// <auto-generated />
using System;
using BooksApi.DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BooksApi.HttpHost.Migrations
{
    [DbContext(typeof(BooksDbContext))]
    [Migration("20180617031452_InitialTestDb")]
    partial class InitialTestDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799");

            modelBuilder.Entity("BooksApi.DataLayer.Book", b =>
                {
                    b.Property<string>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36);

                    b.Property<string>("Author")
                        .HasMaxLength(30);

                    b.Property<string>("BookKindGuid")
                        .HasMaxLength(36);

                    b.Property<int>("ISBN")
                        .HasMaxLength(13);

                    b.Property<string>("Name")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("PublishDate");

                    b.HasKey("Guid");

                    b.HasIndex("BookKindGuid");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("BooksApi.DataLayer.BookKind", b =>
                {
                    b.Property<string>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36);

                    b.Property<string>("Name")
                        .HasMaxLength(20);

                    b.HasKey("Guid");

                    b.ToTable("BookKinds");
                });

            modelBuilder.Entity("BooksApi.DataLayer.BookOrder", b =>
                {
                    b.Property<string>("BookGuid");

                    b.Property<string>("OrderGuid");

                    b.HasKey("BookGuid", "OrderGuid");

                    b.HasIndex("OrderGuid");

                    b.ToTable("BookOrder");
                });

            modelBuilder.Entity("BooksApi.DataLayer.Inventory", b =>
                {
                    b.Property<string>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36);

                    b.Property<string>("BookGuid")
                        .IsRequired()
                        .HasMaxLength(36);

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("ReplenishDate")
                        .ValueGeneratedOnAddOrUpdate();

                    b.HasKey("Guid");

                    b.HasIndex("BookGuid")
                        .IsUnique();

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("BooksApi.DataLayer.Order", b =>
                {
                    b.Property<string>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36);

                    b.Property<DateTime?>("EstimateToDelivery")
                        .HasColumnName("ETD");

                    b.Property<DateTime?>("OrderDate")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("OrderNo")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(1);

                    b.Property<string>("UserGuid");

                    b.HasKey("Guid");

                    b.HasIndex("UserGuid");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("BooksApi.DataLayer.User", b =>
                {
                    b.Property<string>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36);

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("Name")
                        .HasMaxLength(40);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.HasKey("Guid")
                        .HasName("PrimaryKey_UserGuid");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BooksApi.DataLayer.Book", b =>
                {
                    b.HasOne("BooksApi.DataLayer.BookKind", "BookKind")
                        .WithMany("Books")
                        .HasForeignKey("BookKindGuid");
                });

            modelBuilder.Entity("BooksApi.DataLayer.BookOrder", b =>
                {
                    b.HasOne("BooksApi.DataLayer.Book", "Book")
                        .WithMany("BookOrders")
                        .HasForeignKey("BookGuid")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BooksApi.DataLayer.Order", "Order")
                        .WithMany("BookOrders")
                        .HasForeignKey("OrderGuid")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BooksApi.DataLayer.Inventory", b =>
                {
                    b.HasOne("BooksApi.DataLayer.Book", "Book")
                        .WithOne("Inventory")
                        .HasForeignKey("BooksApi.DataLayer.Inventory", "BookGuid")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BooksApi.DataLayer.Order", b =>
                {
                    b.HasOne("BooksApi.DataLayer.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserGuid");
                });
#pragma warning restore 612, 618
        }
    }
}
